export const items = [{
    id: 1,
    name: "Hoodies",
    price: 14.0,
    image: "Assets/images/featured1.png",
    category: "Hoodies",
    quantity: 10,
},
{
    id: 2,
    name: "Shirts",
    price: 24.0,
    image: "Assets/images/featured2.png",
    category: "Shirts",
    quantity: 15,
},
{
    id: 3,
    name: "Sweatshirts",
    price: 24.0,
    image: "Assets/images/featured3.png",
    category: "Shirts",
    quantity: 20,
},
// {
//     id: 4,
//     name: "Sweatshirts",
//     price: 20.0,
//     image: "Assets/images/featured3.png",
//     category: "Shirts",
//     quantity: 15,
// },
// {
//     id: 5,
//     name: "Sweatshirts",
//     price: 16.0,
//     image: "Assets/images/featured3.png",
//     category: "Shirts",
//     quantity: 25,
// },
// {
//     id: 6,
//     name: "Sweatshirts",
//     price: 14.0,
//     image: "Assets/images/featured3.png",
//     category: "Shirts",
//     quantity: 25,
// },
// {
//     id: 7,
//     name: "Sweatshirts",
//     price: 36.0,
//     image: "Assets/images/featured3.png",
//     category: "Shirts",
//     quantity: 5,
// },
// {
//     id: 8,
//     name: "Sweatshirts",
//     price: 36.0,
//     image: "Assets/images/featured3.png",
//     category: "Shirts",
//     quantity: 10,
// },
];